project:
  type: website
  output-dir: docs

website:
  title: "DEBIAS"
  image: images/logo-white.jpeg
  favicon: images/logo-white.jpeg
  # twitter-card:
  #   site: "@fcorowe"
  open-graph: true
  site-url: de-bias.github.io/debias/
  repo-url: https://github.com/de-bias/debias
  repo-actions: [edit, issue]
  # If you are forking our repo to develop content -- whether for Real World Data Science
  # or your own purposes -- please disable our Google Analytics tag during development.
  # If building your own site, replace our GA tag with your own GA tag before deployment.
  # This will prevent your activity being tracked and counted in our analytics dashboard.
  # Thank you!
  # google-analytics: ""
  navbar:
    toggle-position: right
    background: "#f0eeeb"
    logo: images/logo-white.jpeg
    logo-alt: "DEBIAS"
    title: false
    collapse-below: lg
    right:
      - href: index.qmd
        text: Home
      - project/index.qmd
      - updates/index.qmd
      - talks/index.qmd
      - publications/index.qmd


  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    background: "#000000"
    left: |
      [Copyright &copy; 2024 Francisco Rowe, Carmen Cabrera-Arnau]
    center:
      - href: https://github.com/de-bias
        icon: github
        aria-label: GitHub
      # - href:
      #   text: "{{< ai zenodo size=2xl >}}"
      #   aria-label:
      # - href:
      #   icon: linkedin
      #   aria-label: LinkedIn
      # - href:
      #   icon: twitter-x
      #   aria-label: Twitter/X
      # - href:
      #   icon: mastodon
      #   aria-label: Mastodon
      # - href: feeds.html
      #   icon: rss
      #   aria-label:

    # right: |
    #   [Terms & Conditions](/ts-and-cs.qmd)

format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute:
  freeze: auto
